### PR TITLE
Include Honda fluxes at SK for IntegralPreserving. Add IntegralPreserving class for sub-GeV (SG) neutrinos.

### PR DESCRIPTION
**Pull request by pabloferm**
I had to implement these changes on version 2.0.0 and not the latest one, otherwise I could not compile the code.

Please, let me know anything you want me to change.
numu_spectrum_nuflux

### CODE REVIEW

**Comment by kjmeagher** [comment]
If you need help compiling pleas ask for it instead of submitting pull requests that revert recent changes. Also you need to add entries to the unit tests and documentation for you new flux model

**Comment by kjmeagher** [comment]
@pabloferm I looked over this again and it looks like IntegralPreservingFluxSubGeV is identical to IntegralPreservingFlux except for `getMinEnergy()`. Please avoid copy-pasta. Can you just add the min/max energies to the data file and have getMinEnergy()/getMaxEnergy() return those values instead of copying a whole class?

**Comment by pabloferm** [comment]
Thanks a lot for the comments @kjmeagher. I will be mending things soon and let you know.

**Comment by pabloferm** [comment]
Since there was quite a lot to change, I am going to close this PR and start a new one with the appropriate version of the code and the suggested changes. Is that OK?

**Comment by kjmeagher** [comment]
Yes

**Pull request closed without merging**
